bodies:
- id: left-wall
  type: box
  pos: [-10, 4]
  width: 1
  height: 11
  static: true
- id: right-wall
  type: box
  pos: [10, 4]
  width: 1
  height: 11
  static: true
- id: top-wall
  type: box
  pos: [0, 15]
  width: 11
  height: 1
  static: true
# Arm bodies
- id: A
  pos: [0, 1.5]
  width: 0.2
  height: 1.5
  label: A
  color: [0.8, 0.8, 1]
- id: B
  pos: [1, 3]
  width: 2
  height: 0.1
  label: B
  color: [0.8, 0.8, 1]
# Bonus
- &basicBox
  pos: [-2, 2]
  width: 0.4
  height: 0.4
- <<: *basicBox
  pos: [-2, 1]
  density: 6
  color: [0.2, 0.2, 0.2]
- <<: *basicBox
  pos: [-2, 3]
- <<: *basicBox
  pos: [-2, 4]
- <<: *basicBox
  pos: [-2, 5]


joints:
- type: revolute
  bodyA: _ground
  bodyB: A
  anchor: [0,0]
  enableLimit: true
  lowerAngle: -0.35
  upperAngle: 0.35
- type: revolute
  bodyA: A
  bodyB: B
  anchor: [0, 3]
  enableLimit: true
  lowerAngle: -0.4
  upperAngle: 0.4


elastics:
- id: a1
  bodyA: _ground
  bodyB: A
  anchorA: [-1.5, -1]
  anchorB: [-0.4, 0.8]
  k: 400
  damping: 10
- id: a2
  bodyA: _ground
  bodyB: A
  anchorA: [1.5, -1]
  anchorB: [0.4, 0.6]
  k: 400
  damping: 10
- id: b1
  bodyA: _ground
  bodyB: B
  anchorA: [-1, -1]
  anchorB: [-0.6, 3]
  k: 300
  damping: 10
  contacts:
  - body: A
    point: [-0.3, 0.8]
  - body: A
    point: [-0.3, 1.5]
- id: b2
  bodyA: _ground
  bodyB: B
  anchorA: [1, -1]
  anchorB: [0.6, 3]
  k: 300
  damping: 10
  contacts:
  - body: A
    point: [0.3, 0.6]
  - body: A
    point: [0.3, 1.5]


tendon-controllers:
- elastic: a1
  label: A Extensor
- elastic: a2
  label: A Flexor
- elastic: b1
  label: B Extensor
- elastic: b2
  label: B Flexor


coupled-controllers:
- extensor: a1
  flexor: a2
  label: A
- extensor: b1
  flexor: b2
  label: B


loads:
- body: B
  anchor: [3, 3]
  max: 800
